<Project>
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <!-- Copia automática de pdfium.dll (x86 y x64) al bin -->
  <Target Name="CopyPdfiumNative" AfterTargets="Build">
    <ItemGroup>
      <PdfiumFiles Include="$(MSBuildProjectDirectory)\..\packages\PdfiumViewer.Native.*\runtimes\win-x64\native\pdfium.dll" Condition="Exists('%(Identity)')" />
      <PdfiumFiles Include="$(MSBuildProjectDirectory)\..\packages\PdfiumViewer.Native.*\runtimes\win-x86\native\pdfium.dll" Condition="Exists('%(Identity)')" />
    </ItemGroup>
    <Copy SourceFiles="@(PdfiumFiles)" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" />
  </Target>
</Project>